FROM node:16-alpine3.12
RUN mkdir /frontend
WORKDIR /frontend
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install

COPY public public
COPY src src

EXPOSE 3000

CMD ["npm", "start"]